apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-deploy
  namespace: ingress-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: ip-nginx
          image: 192.168.0.195:5000/ipnginx

