apiVersion: apps/v1
kind: Deployment
metadata:
  name: n-deploy
  namespace: ingress-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 192.168.0.195:5000/nginx:latest

---
apiVersion: v1
kind: Service
metadata:
  name: n-svc
  namespace: ingress-nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30070
  selector:
    app: nginx
  type: NodePort
