apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  labels:
    app: wordpress
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.160
    path: /mysql
    readOnly: false
