apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: 192.168.0.195:5000/nginx:1.14.0
        ports:
        - containerPort: 80
