apiVersion: apps/v1
kind: Deployment
metadata:
  name: hnginx-deploy
  labels:
    app: hnginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hnginx
  template:
    metadata:
      labels:
        app: hnginx
    spec:
      containers:
      - name: hnginx-container
        image: 192.168.0.195:5000/hnginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hnginx-svc
spec:
  selector:
    app: hnginx
  ports:
    - name: hnginx-svc
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32767
  type: NodePort
