apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-deploy
  namespace: metallb-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomnginx
  template:
    metadata:
      labels:
        app: tomnginx
    spec:
      containers:
        - name: ipnginx
          image: 192.168.0.195:5000/tom
---
apiVersion: v1
kind: Service
metadata:
  name: tom-svc
  namespace: metallb-system
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tomnginx
  type: LoadBalancer
